[build.environment]
  NODE_VERSION = "20"

[build]  
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  functions = "netlify/functions"
  publish = "dist"
  port = 8888
